### ISSUE TITLE
Not compatible with the latest laravel 

### ISSUE THREAD

**Issue by darkshifty** [itsnubix/nowcal#1]
itsnubix/nowcal 0.2.0 requires illuminate/support ^6.0

**Comment by kylemilloy** [comment]
Updating `illuminate/support` to `"~5.8.0|^6.0|^7.0"`...will update packagist in a bit here....

**Comment by kylemilloy** [comment]
Release 0.3.0 is now out and adds support for L5/6/7

**Comment by darkshifty** [comment]
You are too fast! thank you!

**Comment by kylemilloy** [comment]
Nah...you've just got good timing :). You're welcome.
